

# --------------------------------------------------------------------------- #
# --------------------------------------------------------------------------- #
#
# run_weib3_idt.R
#
# -- Code originally by Philip Labuschagne
# -- Adapted for use and executed by C.A. Magaret (cmagaret@fredhutch.org)
#
# Uses input files generated by the "amp_dx_history_preprocessing.R" script, 
# located in the "1_data_preparation" directory.
#
# Originally run on 19 June 2020 on the following files:
#   "AMP_diagnostic_testing_history_primary_2020_May_v1_all_for_weib3IDT.csv"
#   "AMP_diagnostic_testing_history_primary_2020_May_v1_all_invalid_histories.csv"
#
# --------------------------------------------------------------------------- #
# --------------------------------------------------------------------------- #


# refresh our workspace
rm (list=ls ())

# devtools::install_github('philliplab/tsic')
library (ggplot2)

# CONFIG:  define the path to the directory of support files (including the
# prototype "tsic2" package)
path.support <- "/file/path/code/0_support"
path.support <- "~/Downloads/AMP_InfectionTimingEstimation/code/0_support"

# load tsic2 files and supplement
setwd (file.path (path.support, "tsic2/data"))
load ("all_assay_dynamics.rda")
setwd (file.path (path.support, "tsic2/R"))
source ("assay_dynamics.R")
source ("result_interpretation.R")
source ("interpretation_processing.R")
source ("DSHIVInfectionTiming.R")
source ("interpretation_presentation.R")
setwd (path.support)
source ("tsic2_supplement.Rlib")

# CONFIG:  which set are we running this for?
input_file <- 'AMP_diagnostic_testing_history_primary_2020_May_v1_all_for_weib3IDT.csv'
invalid_histories_file <- 'AMP_diagnostic_testing_history_primary_2020_May_v1_all_invalid_histories.csv'
data_folder <- '/file/path/input/files'
results_folder <- '/file/path/results'
plots_folder <- '/file/path/plots'

data_folder <- '/centernet/bioinfo/sponsors/nih/hvtn/hvtn703_704/sieve/analysis/cmagaret/04_inf_time_est/3.go/dat/work/preprocess_all'
results_folder <- '/centernet/bioinfo/sponsors/nih/hvtn/hvtn703_704/sieve/analysis/cmagaret/04_inf_time_est/3.go/results/all/grebe'
plots_folder <- '/centernet/bioinfo/sponsors/nih/hvtn/hvtn703_704/sieve/analysis/cmagaret/04_inf_time_est/3.go/results/all/grebe/plots'

# CONFIG:  how many ptids do you want to run?  (for debugging; select "all" for running on the actual data
#how_many <- 10
how_many <- 'all'

# load the input data
setwd (data_folder)
dat <- read.csv(input_file, stringsAsFactors = FALSE)
invalid_ptids <- read.csv(invalid_histories_file, stringsAsFactors = FALSE)

# specify how many participants to run on
if (how_many == 'all'){
  how_many <- length(setdiff(unique(dat$ptid), invalid_ptids$ptid))
}

# calculate the estimates for each participant
all_results <- NULL
for (c_ptid in setdiff(unique(dat$ptid), invalid_ptids$ptid)[1:how_many]){
  print(c_ptid)
  c_hist <- subset(dat, ptid == c_ptid)
  c_hist$sample_date <- as.numeric( c_hist$sample_date ) + 0.5; # start at noon.
  agg_inter <- construct_aggregate_interpreter(c_hist)

  range_start <- floor(min(c_hist$sample_date) - 100)
  range_end <- ceiling(max(c_hist$sample_date) + 30)

  lb_med_ub <- estimate_lb_med_ub(fun = agg_inter,
    range_start = range_start,
    range_end = range_end,
    label = c_ptid)

  daily_grid <- compute_daily_grid(agg_fun = agg_inter,
                                   tauc = lb_med_ub$aoc,
                                   range_start = range_start,
                                   range_end = range_end)

  c_result <- daily_grid[, c('interval_start', 'interval_end', 'mass')]
  c_result$ptid <- c_ptid
  c_result <- c_result[, c('ptid', 'interval_start', 'interval_end', 'mass')]

  c_result <-
  merge(c_result, 
    data.frame(lb_rounded = as.character(as.Date(floor(lb_med_ub$lb), origin = '1970-01-01')),
               med_rounded = as.character(as.Date(round(lb_med_ub$med, 0), origin = '1970-01-01')),
               ub_rounded = as.character(as.Date(ceiling(lb_med_ub$ub), origin = '1970-01-01')),
               interval_width_days = lb_med_ub$ub - lb_med_ub$lb,
               lb_unrounded = paste(as.character(as.Date(floor(lb_med_ub$lb), origin = '1970-01-01')),
                                   format(as.POSIXct((lb_med_ub$lb - floor(lb_med_ub$lb))*60*60*24, 
                                                     origin = '1970-01-01', tz = 'GMT'), "%H:%M:%S"),
                                   sep = ' '),
               med_unrounded = paste(as.character(as.Date(floor(lb_med_ub$med), origin = '1970-01-01')),
                                   format(as.POSIXct((lb_med_ub$med - floor(lb_med_ub$med))*60*60*24, 
                                                     origin = '1970-01-01', tz = 'GMT'), "%H:%M:%S"),
                                   sep = ' '),
               ub_unrounded = paste(as.character(as.Date(floor(lb_med_ub$ub), origin = '1970-01-01')),
                                   format(as.POSIXct((lb_med_ub$ub - floor(lb_med_ub$ub))*60*60*24, 
                                                     origin = '1970-01-01', tz = 'GMT'), "%H:%M:%S"),
                                   sep = ' '),
               notes = 'No Anomalies',
               lb_internal = lb_med_ub$lb,
               med_internal = lb_med_ub$med,
               ub_internal = lb_med_ub$ub,
               stringsAsFactors = FALSE
    ),
    by = NULL)

  all_results <- rbind(all_results, c_result)
  
  p1 <-
  plot_iihist(c_hist, lb_med_ub = lb_med_ub, 
              range_start = range_start, range_end = range_end, 
              plot_aggregate = TRUE, produce_plot = FALSE)
  ggsave(paste0(plots_folder, '/weib3_idt_', c_ptid, '.png'),
         plot = p1)
  if (FALSE){
    plot_iihist(c_hist, lb_med_ub = NULL, 
                range_start = range_start, range_end = range_end, 
                plot_aggregate = FALSE, produce_plot = FALSE)
  }
}

all_results$day <- as.character(as.Date(all_results$interval_start, origin = '1970-01-01'))
all_results$FLAG <- 'Processed without issues'

trans_results <- all_results[, c('ptid',
                                 'day', 
                                 'mass',
                                 'lb_rounded',
                                 'med_rounded',
                                 'ub_rounded',
                                 'interval_width_days',
                                 'FLAG',
                                 'lb_unrounded',
                                 'med_unrounded',
                                 'ub_unrounded')]

names(trans_results) <- c('ptid', 'day', 'mass', 
                          'LB_tsic_dee_rounded', 'MEDIAN_tsic_dee_rounded', 'UB_tsic_dee_rounded',
                          'interval_length_tsic', 'FLAG',
                          'LB_tsic_dee_unrounded', 'MEDIAN_tsic_dee_unrounded', 'UB_tsic_dee_unrounded')
all_results <- trans_results

# export the results
setwd (results_folder)
write.csv(all_results, 
          gsub('for_weib3IDT.csv', 'weib3IDT_results.csv', input_file),
          row.names = FALSE)

